name: CI/CD - CloudTaskManager

on:
  push:
    branches:
      - main

jobs:

  # =========================
  # CI - Build & Push Images
  # =========================
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cloudtask-backend:latest

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cloudtask-frontend:latest


  # =========================
  # CD - Deploy to EC2
  # =========================
  deploy:
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            echo "================================="
            echo "Starting CloudTaskManager deploy"
            echo "================================="

            cd ~/cloudtask

            echo "Pulling latest Docker images..."
            docker compose pull backend frontend

            echo "Updating application containers..."
            docker compose up -d backend frontend

            echo "Checking containers..."
            docker compose ps

            echo "Deployment completed!"